services:
  - type: web
    name: rezerviraj-backend
    env: node
    plan: free
    region: oregon
    build_command: "npm install && npm run build || true"
    start_command: "npm run start"
    auto_deploy: true
    branch: main
    env:
      - key: MONGODB_URL
        value: ""
      - key: JWT_SECRET
        value: ""
      - key: SMTP_HOST
        value: ""
      - key: SMTP_PORT
        value: ""
      - key: SMTP_USER
        value: ""
      - key: SMTP_PASS
        value: ""
      - key: SMTP_FROM
        value: ""
      - key: MAIL_REDIRECT_TO
        value: ""

static_sites:
  - name: rezerviraj-frontend
    repo: .
    branch: main
    root: frontend
    build_command: "npm install && npm run build"
    publish_dir: dist
    env:
      - key: VITE_BACKEND_URL
        value: ""
    auto_deploy: true

  - name: rezerviraj-admin
    repo: .
    branch: main
    root: admin
    build_command: "npm install && npm run build"
    publish_dir: dist
    env: []
    auto_deploy: true
